apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccp-frontend-deploy
  namespace: trove-web-app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: ccp-frontend-service-app
  replicas: {{REPLICAS}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ccp-frontend-service-app
    spec:
      containers:
        - name: ccp-frontend-service-app
          image: 139616021341.dkr.ecr.eu-west-2.amazonaws.com/trove/ccp-frontend:{{BITBUCKET_COMMIT}}
          imagePullPolicy: Always
          ports:
              - containerPort: 8080
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "500m"